### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [richardfearn/mythcal#15]
```
Running the latest up-to-date git pull (v0.27.0) with my sleep(0.25) in the 
loops I occasionally get the following error.

Traceback (most recent call last):
  File "./mythcal", line 269, in <module>
    delete_existing_events()
  File "./mythcal", line 232, in delete_existing_events
    print "    will delete \"%s\"" % item["summary"]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 
51: ordinal not in range(128)

```

Original issue reported on code.google.com by `zeak...@gmail.com` on 2 Mar 2015 at 9:59

**Comment by richardfearn** [comment]
Now that mythcal has been converted to Python 3, I don't expect any more character encoding issues.
